[variable_params]
mchirp = 
q =  
spin1z =
spin2z =
inclination =  
tc = 
ra = 
dec = 
coa_phase =
polarization =
distance = 
acc = 
eccentricity = 
rel_anomaly = 

[static_params]
approximant = constlosAcc
base_model = SEOBNRv5EHM
v0 = 0
f_lower = 20
f_ref = 20
trigger_time = 1262276684.06
n = 0.1
taper = TAPER_NONE
lmax_nyquist=1
lambda1 = 0
lambda2 = 0
tw = 0.08

[prior-mchirp]
name = mchirp_from_uniform_mass1_mass2
min-mchirp = 3.00
max-mchirp = 4.00

[prior-q]
name = q_from_uniform_mass1_mass2
min-q = 1.0
max-q = 19.0

[prior-spin1z]
name = uniform
min-spin1z = -0.99
max-spin1z = 0.99

[prior-spin2z]
name = uniform
min-spin2z = -0.99
max-spin2z = 0.99

[waveform_transforms-mass1]
name = custom
inputs = mchirp, q
mass1 = mass1_from_mchirp_q(mchirp, q)

[waveform_transforms-mass2]
name = custom
inputs = mchirp, q
mass2 = mass2_from_mchirp_q(mchirp, q)

[prior-ra]
name = uniform_angle

[prior-dec]
name = cos_angle

[prior-tc]
#; coalescence time prior
name = uniform
min-tc = 1262276683.86
max-tc = 1262276684.26

[prior-distance]
#; following gives a uniform in volume
name = uniform_radius
min-distance = 50
max-distance = 550 


[prior-polarization]
name = uniform_angle

[prior-inclination]
name = sin_angle

[prior-coa_phase]
name = uniform_angle

[prior-acc]
name = uniform
min-acc = -0.05
max-acc = 0.05

[prior-rel_anomaly]
name = uniform_angle

[prior-eccentricity]
name = uniform
min-eccentricity = 0.01000
max-eccentricity = 0.01500

[model]
name = marginalized_time
sample_rate = 4096
marginalize_vector_params = tc, ra, dec, polarization
marginalize_vector_samples = 5000
low-frequency-cutoff = H1:20 L1:21 V1:20
ignore-failed-waveforms = 

marginalize_phase = False
marginalize_distance = True
marginalize_distance_param = distance
marginalize_distance_interpolator = True
marginalize_distance_snr_range = 1, 30

marginalize_distance_density = 200, 200
marginalize_distance_samples = 10000 

[sampler]
name = dynesty
dlogz = 0.1
nlive = 2000
walks = 100
sample = rwalk
checkpoint_time_interval = 1800

[data]
instruments = L1
trigger-time = 1262276684.06
analysis-start-time = -99
analysis-end-time = 5
psd-estimation = median-mean
psd-start-time = -256
psd-end-time = 256
psd-inverse-length = 8
psd-segment-length = 8
psd-segment-stride = 4
frame-files = L1:/home/lroy02/acceleration_runs/separate_runs/GW200105/L-L1_GWOSC_16KHZ_R1-1262274636-4096.gwf
channel-name =  L1:GWOSC-16KHZ_R1_STRAIN
sample-rate = 4096
strain-high-pass = 15
pad-data = 8

